app/urls.py
from django.urls import path
from . import views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('artykuly/', views.articles, name='article'),
    path('artykul/<slug:slug>/', views.article, name='article'),
    path('comment/', views.comment, name='comment'),
    path('drobne-ogloszenia/<slug:slug>/', views.small_ads, name='small_ads'),
    path('artykuly/<slug:slug>/', views.articles, name='articles'),
    path('cennik/wydanie-gazetowe/', views.pricing_paper, name='pricing_paper'),
    path('cennik/wydanie-internetowe/', views.pricing_internet, name='pricing_internet'),
    path('wyszukiwarka/', views.search, name='search'),
    path('o-nas/', views.about, name='about'),
    path('kontakt/', views.contact, name='contact'),
    path('polityka-prywatnosci/', views.privacy, name='privacy'),
    path('regulamin-strony/', views.regulations, name='regulations'),
    path('ogloszenia/create/', views.add_create, name='add_create'),
    path('ogloszenia/', views.add_list, name='add_list'),
    path('ogloszenia/<slug:slug>/', views.add_list, name='add_list'),
    path('ogloszenia_detail/<slug:slug>/', views.add_detail, name='add_list'),
    path('subscribe_email/', views.subscribe_email, name='subscribe_email'),
    path('payment_ok/', views.payment_ok, name='payment_ok'),
    path('payment_error/', views.payment_ok, name='payment_error'),
    path('full_access/', views.full_access, name='full_access'),
    path('subscribe/', views.subscribe, name="subscribe"),
    path('update_user/', views.update_user, name='update_user'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('uwierzytelnienie/', include('authentication.urls', namespace='authentication')),
    path('cms/', include('simple_cms.urls', namespace='simple_cms')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from .views import LogIn, SignUp

app_name = 'authentication'

urlpatterns = [
    path('', LogIn.as_view(), name='login'),
    path('nowe-konto/', SignUp.as_view(), name='signup'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    premium = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    surname = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    zip_code = models.CharField(max_length=100, blank=True, null=True)
    telephone = models.CharField(max_length=100, blank=True, null=True)
    business = models.CharField(max_length=100, blank=True, null=True)
    tax_id = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Konta użytkowników'
        verbose_name_plural = 'Konta użytkowników'

authentication/views.py
from django.shortcuts import render
from allauth.account.views import LoginView, SignupView



class LogIn(LoginView):
    template_name = 'authentication/login.html'



class SignUp(SignupView):
    template_name = 'authentication/signup.html'

authentication/templates/authentication/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
  <title>{{ object.title }} - TIT - Tomaszowski Informator Tygodniowy</title>
  <!-- META -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!--::::: FABICON ICON :::::::-->
  <link rel="icon" href="{% static 'assets/img/icon/fabicon.png' %}">
  <!--::::: ALL CSS FILES :::::::-->
  <link rel="stylesheet" href="{% static 'assets/css/plugins/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/stellarnav.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/modal-video.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/slick.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>

<body class="theme-1">
  {% include "app/basic/navbar.html" %}


  <!--::::: LATEST BLOG AREA END :::::::-->
  <div class="space-60"></div>
  <!--:::::  COMMENT FORM AREA START :::::::-->
  <div class="comment_form">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-10 m-auto" id="formularzKomentarzy">
          <h3 id="comment_list" class="mb-4">Zaloguj się</h3>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input name="article_id" type="hidden" value="{{ object.id }}">
            <div class="row">
              <div class="col-md-12">
                <label class="form-control-label">Adres email</label>
                {{ form.login }}
              </div>
              <div class="col-md-12">
                <div class="d-flex align-items-center justify-content-between">
                  <div>
                    <label class="form-control-label">Hasło</label>
                  </div>
                  <div class="mb-2">
                    <a href="#!" class="small text-muted text-underline--dashed border-primary">Nie pamietasz hasła?</a>
                  </div>
                </div>
                {{ form.password }}
              </div>
              <div class="col-12 text-right mb-2">
                <span class="small text-muted text-underline--dashed border-primary">Nie masz jeszcze konta? <a href="{% url 'authentication:signup' %}">Zapisz się</a>.</span>
              </div>
              <div class="col-12 text-right">
                <button type="submit" value="Dodaj komentarz" class="btn btn-primary btn-lg">Zaloguj się</button>
              </div>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="space-100"></div>
  <!--:::::  COMMENT FORM AREA END :::::::-->
  <!--::::: BANNER AREA START :::::::-->
  <div class="padding5050 fourth_bg">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 m-auto">
          <div class="banner1">
            <a href="#">
              <img src="{% static 'assets/img/bg/banner1.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--::::: BANNER AREA END :::::::-->
  <!--::::: FOOTER AREA START :::::::-->
  {% include "app/basic/footer.html" %}

  <!--::::: FOOTER AREA END :::::::-->
  <!--::::: ALL JS FILES :::::::-->
  <script src="{% static 'assets/js/plugins/jquery.2.1.0.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.nav.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery-modal-video.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/owl.carousel.js' %}"></script>
  <script src="{% static 'assets/js/plugins/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/circle-progress.js' %}"></script>
  <script src="{% static 'assets/js/plugins/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/wow.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/stellarnav.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

authentication/templates/authentication/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
  <title>{{ object.title }} - TIT - Tomaszowski Informator Tygodniowy</title>
  <!-- META -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!--::::: FABICON ICON :::::::-->
  <link rel="icon" href="{% static 'assets/img/icon/fabicon.png' %}">
  <!--::::: ALL CSS FILES :::::::-->
  <link rel="stylesheet" href="{% static 'assets/css/plugins/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/stellarnav.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/modal-video.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/slick.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>

<body class="theme-1">
  {% include "app/basic/navbar.html" %}


  <!--::::: LATEST BLOG AREA END :::::::-->
  <div class="space-60"></div>
  <!--:::::  COMMENT FORM AREA START :::::::-->
  <div class="comment_form">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-10 m-auto" id="formularzKomentarzy">
          <h3 id="comment_list" class="mb-4">Zaloguj się</h3>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input name="article_id" type="hidden" value="{{ object.id }}">
            <div class="row">
              <div class="col-md-12">
                <label class="form-control-label">Adres email</label>
                {{ form.email }}
              </div>
              <div class="col-md-12">
                <label class="form-control-label">Hasło</label>
                {{ form.password1 }}
              </div>
              <div class="col-md-12">
                <label class="form-control-label">Powtórz hasło</label>
                {{ form.password2 }}
              </div>
              <div class="col-12 text-right mb-2">
                <span class="small text-muted text-underline--dashed border-primary">Masz już konto? <a href="{% url 'authentication:login' %}">Zaloguj się</a>.</span>
              </div>
              <div class="col-12 text-right">
                <button type="submit" value="Dodaj komentarz" class="btn btn-primary btn-lg">Zapisz się</button>
              </div>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="space-100"></div>
  <!--:::::  COMMENT FORM AREA END :::::::-->
  <!--::::: BANNER AREA START :::::::-->
  <div class="padding5050 fourth_bg">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 m-auto">
          <div class="banner1">
            <a href="#">
              <img src="{% static 'assets/img/bg/banner1.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--::::: BANNER AREA END :::::::-->
  <!--::::: FOOTER AREA START :::::::-->
  {% include "app/basic/footer.html" %}

  <!--::::: FOOTER AREA END :::::::-->
  <!--::::: ALL JS FILES :::::::-->
  <script src="{% static 'assets/js/plugins/jquery.2.1.0.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.nav.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery-modal-video.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/owl.carousel.js' %}"></script>
  <script src="{% static 'assets/js/plugins/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/circle-progress.js' %}"></script>
  <script src="{% static 'assets/js/plugins/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/wow.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/stellarnav.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>