app/urls.py
from django.urls import path
from . import views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('artykuly/', views.articles, name='article'),
    path('artykul/<slug:slug>/', views.article, name='article'),
    path('comment/', views.comment, name='comment'),
    path('drobne-ogloszenia/<slug:slug>/', views.small_ads, name='small_ads'),
    path('artykuly/<slug:slug>/', views.articles, name='articles'),
    path('cennik/wydanie-gazetowe/', views.pricing_paper, name='pricing_paper'),
    path('cennik/wydanie-internetowe/', views.pricing_internet, name='pricing_internet'),
    path('wyszukiwarka/', views.search, name='search'),
    path('o-nas/', views.about, name='about'),
    path('kontakt/', views.contact, name='contact'),
    path('polityka-prywatnosci/', views.privacy, name='privacy'),
    path('regulamin-strony/', views.regulations, name='regulations'),
    path('ogloszenia/create/', views.add_create, name='add_create'),
    path('ogloszenia/', views.add_list, name='add_list'),
    path('ogloszenia/<slug:slug>/', views.add_list, name='add_list'),
    path('ogloszenia_detail/<slug:slug>/', views.add_detail, name='add_list'),
    path('subscribe_email/', views.subscribe_email, name='subscribe_email'),
    path('payment_ok/', views.payment_ok, name='payment_ok'),
    path('payment_error/', views.payment_ok, name='payment_error'),
    path('full_access/', views.full_access, name='full_access'),
    path('subscribe/', views.subscribe, name="subscribe"),
    path('update_user/', views.update_user, name='update_user'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('uwierzytelnienie/', include('authentication.urls', namespace='authentication')),
    path('cms/', include('simple_cms.urls', namespace='simple_cms')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/basic/footer.html
{% load static %}
	<div class="footer footer_area1 primay_bg">
		<div class="container">
			<div class="cta">
				<div class="row">
					<div class="col-md-6 align-self-center">
						<div class="social2">
							<ul class="inline">
								<li><a href="#" class="not-active"><i class="fab fa-facebook-f"></i></a>
								</li>
								<li><a href="#" class="not-active"><i class="fab fa-youtube"></i></a>
								</li>
								<li><a href="#" class="not-active"><i class="fab fa-instagram"></i></a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-md-6 col-lg-4 offset-lg-2 align-self-center">
						<div class="signup_form">
							<form action="#" method="post">
								<input class="signup" type="email" placeholder="Twój adres email">
								<input type="button" class="cbtn" value="Zapisz się">
							</form>
							<p class="text-white">Subskrybuj nas i bądź na bieżąco</p>
						</div>
					</div>
				</div>
			</div>
			<div class="border_white"></div>
			<div class="space-40"></div>
			<div class="row justify-content-center">
				<div class="col-lg-8">
					<div class="row">
						<div class="col-sm-6 col-lg">
							<div class="single_footer_nav border_white_right">
								<h3 class="widget-title2">Artykuły</h3>
								<div class="row">
									<div class="col-lg-6">
										<ul>
											<li><a href="#">Politics</a>
											</li>
											<li><a href="#">Business</a>
											</li>
											<li><a href="#">TECHNOLOGY</a>
											</li>
											<li><a href="#">Science</a>
											</li>
											<li><a href="#">Health</a>
											</li>
											<li><a href="#">Sports</a>
											</li>
											<li><a href="#">Entertainment</a>
											</li>
										</ul>
									</div>
									<div class="col-lg-6">
										<ul>
											<li><a href="#">Education</a>
											</li>
											<li><a href="#">Obituaries</a>
											</li>
											<li><a href="#">Corrections</a>
											</li>
											<li><a href="#">Education</a>
											</li>
											<li><a href="#">Today’s Paper</a>
											</li>
											<li><a href="#">Corrections</a>
											</li>
											<li><a href="#">Foods</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-lg">
							<div class="single_footer_nav">
								<h3 class="widget-title2">Drobne ogłoszenia</h3>
								<div class="row">
									<div class="col-lg-6">
										<ul>
											<li><a href="#">Crossword</a>
											</li>
											<li><a href="#">Food</a>
											</li>
											<li><a href="#">Automobiles</a>
											</li>
											<li><a href="#">Education</a>
											</li>
											<li><a href="#">Health</a>
											</li>
											<li><a href="#">Magazine</a>
											</li>
											<li><a href="#">Weddings</a>
											</li>
										</ul>
									</div>
									<div class="col-lg-6">
										<ul>
											<li><a href="#">Classifieds</a>
											</li>
											<li><a href="#">Photographies</a>
											</li>
											<li><a href="#">NYT Store</a>
											</li>
											<li><a href="#">Journalisms</a>
											</li>
											<li><a href="#">Public Editor</a>
											</li>
											<li><a href="#">Tools & Services</a>
											</li>
											<li><a href="#">My Account</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="space-40"></div>
        </div>
				<div class="col-lg-4">
					<div class="extra_newss border_white_left pl-4">
						<div class="footer_contact">
							<h3 class="widget-title2">Kontakt z redakcją</h3>
							<div class="single_fcontact">
								<div class="fcicon">
									<img src="{% static 'assets/img/icon/mobile.png' %}" alt="">
								</div>	<a href="#">On your mobile</a>
							</div>
							<div class="single_fcontact">
								<div class="fcicon">
									<img src="{% static 'assets/img/icon/speacker.png' %}" alt="">
								</div>	<a href="#">On smart speakers</a>
							</div>
							<div class="single_fcontact">
								<div class="fcicon">
									<img src="{% static 'assets/img/icon/evelope.png' %}" alt="">
								</div>	<a href="#">Contact Newspark news</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 align-self-center">
						<p>&copy; Copyright 2020, All Rights Reserved</p>
					</div>
					<div class="col-lg-6 align-self-center">
						<div class="copyright_menus text-right">
							<div class="language"></div>
							<div class="copyright_menu inline">
								<ul>
									<li><a href="{% url 'app:privacy' %}">Polityka prywatności</a>
									</li>
									<li><a href="{% url 'app:regulations' %}">Regulamin</a>
									</li>
									<li><a href="#">Reklama</a>
									</li>
									<li class="text-white"><a href="https://tgcoders.pl/" target="_blank">Create by TGcoders.pl</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
  
  

app/templates/app/basic/footer_banner.html
{% load app_tags %}

<div class="padding5050 fourth_bg">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 m-auto">
          <div class="banner1">
             {% get_random_add  as random_add %}
                {% if random_add %}
                    {% for item in random_add %}
                        {% with item.url|add:',/artykul/'|add:item.slug  as url_str %}
                        <a  href="{{ item.add|yesno:url_str }}"  target="{{ item.add|yesno:'_blank,_self' }}">
                            <img src="{{ item.img_728x90.url }}" alt="{{ item.title }}">
                        </a>
                        {% endwith %}
                    {% endfor %}
                {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

app/templates/app/basic/latest_article.html
{% load app_tags %}

<div class="fourth_bg padding6030">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="heading">
            <h2 class="widget-title">Najnowsze artykuły</h2>
          </div>
        </div>
      </div>
      <div class="row justify-content-center">
          {% get_random_article as random_articles %}
          {% if random_articles %}
              {% for item in random_articles %}
                  {% with item.url|add:',/artykul/'|add:item.slug  as url_str %}
                  <div class="col-md-6 col-lg-4">
                      <div class="single_post post_type3 mb30">
                        <div class="post_img">
                          <a  href="{{ item.add|yesno:url_str }}"  target="{{ item.add|yesno:'_blank,_self' }}">
                            <img src="{{ item.img_700x500.url }}" alt="{{ item.title }}">
                          </a>
                        </div>
                        <div class="single_post_text">
                          <div class="meta3"> <a href="/artykul/{{ item.slug }}/" target="{{ item.add|yesno:'_blank,_self' }}">{{ item.category.name }}</a>
                            <a  href="{{ item.add|yesno:url_str }}"  target="{{ item.add|yesno:'_blank,_self' }}">{{item.date_of_publication|date:"SHORT_DATE_FORMAT" }}</a>
                          </div>
                          <h4><a  href="{{ item.add|yesno:url_str }}"  target="{{ item.add|yesno:'_blank,_self' }}">{{ item.title |truncatechars:27}}</a></h4>
                          <div class="space-10"></div>
                          <p class="post-p">{{ item.subtitle|truncatechars:120 }}</p>
                        </div>
                      </div>
                    </div>
                  {% endwith %}
              {% endfor %}
          {% endif %}

      </div>
    </div>
  </div>

app/templates/app/basic/navbar.html
{% load static %}
{% load app_tags %}
<!--::::: PRELOADER START :::::::-->
<div class="preloader">
    <div>
        <div class="nb-spinner"></div>
    </div>
</div>
<!--::::: PRELOADER END :::::::-->

<!--::::: SEARCH FORM START:::::::-->
<div class="searching">
    <div class="container">
        <div class="row">
            <div class="col-8 text-center m-auto">
                <div class="v1search_form">
                    <form action="/artykuly/">
                        <input type="search" name="search" placeholder="Wpisz szukaną frazę..."  >
                        <button type="submit" class="cbtn1">Wyszukaj</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="close_btn"><i class="fal fa-times"></i>
    </div>
</div>
<!--:::::SEARCH FORM END :::::::-->

<!--::::: TOP BAR START :::::::-->
<div class="topbar white_bg" id="top">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 align-self-center">
                <div class="trancarousel_area">
                    <p class="trand">Na bieżąco</p>
                    <div class="trancarousel owl-carousel nav_style1">
                        {% if object.navbar_alert_1 %}
                            <div class="trancarousel_item openModalClass" onclick="passDataFunction('navbar_alert_1')">
                                <p>
                                    {% with object.navbar_alert_1.url|add:',/artykul/'|add:object.navbar_alert_1.slug  as url_str %}
                                    <a href="{{ object.navbar_alert_1.add|yesno:url_str }}"  target="{{ object.navbar_alert_1.add|yesno:'_blank,_self' }}">
                                    {{ object.navbar_alert_1.title|truncatechars:50 }}</a>
                                    {% endwith %}
                                </p>
                            </div>
                        {% endif %}
                        {% if object.navbar_alert_2 %}
                            <div class="trancarousel_item openModalClass" onclick="passDataFunction('navbar_alert_2')">
                                <p>
                                    {% with object.navbar_alert_2.url|add:',/artykul/'|add:object.navbar_alert_2.slug  as url_str %}
                                    <a  href="{{ object.navbar_alert_2.add|yesno:url_str }}"  target="{{ object.navbar_alert_2.add|yesno:'_blank,_self' }}">
                                    {{ object.navbar_alert_1.title|truncatechars:50 }}</a>
                                    {% endwith %}
                                </p>
                            </div>
                        {% endif %}
                        {% if object.navbar_alert_3 %}
                            <div class="trancarousel_item openModalClass" onclick="passDataFunction('navbar_alert_3')">
                                <p>
                                    {% with object.navbar_alert_3.url|add:',/artykul/'|add:object.navbar_alert_3.slug  as url_str %}
                                    <a href="{{ object.navbar_alert_3.add|yesno:url_str }}" target="{{ object.navbar_alert_3.add|yesno:'_blank,_self' }}">
                                        {{ object.navbar_alert_3.title|truncatechars:50 }}</a>
                                    {% endwith %}
                                </p>
                            </div>
                        {% endif %}
                        {% if object.navbar_alert_4 %}
                            <div class="trancarousel_item openModalClass" onclick="passDataFunction('navbar_alert_4')">
                                <p>
                                    {% with object.navbar_alert_4.url|add:',/artykul/'|add:object.navbar_alert_4.slug  as url_str %}
                                    <a  href="{{ object.navbar_alert_4.add|yesno:url_str }}"  target="{{ object.navbar_alert_4.add|yesno:'_blank,_self' }}">
                                        {{ object.navbar_alert_4.title|truncatechars:50 }}</a>
                                    {% endwith %}
                                </p>
                            </div>
                        {% endif %}
                        {% if object.navbar_alert_5 %}
                            <div class="trancarousel_item openModalClass" onclick="passDataFunction('navbar_alert_5')">
                                <p>
                                    {% with object.navbar_alert_5.url|add:',/artykul/'|add:object.navbar_alert_5.slug  as url_str %}
                                        <a  href="{{ object.navbar_alert_5.add|yesno:url_str }}"  target="{{ object.navbar_alert_5.add|yesno:'_blank,_self' }}">
                                            {{ object.navbar_alert_5.title|truncatechars:50 }}</a>
                                    {% endwith %}
                                </p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 align-self-center">
                <div class="top_date_social text-right">
                    <div class="paper_date">
                        <p>
                            <a class="btn btn-sm btn-danger" href="/ogloszenia/create/" style="color:#fff">Dodaj ogłoszenie</a>
                        </p>
                    </div>
                    <div class="social1">
                        <ul class="inline">
                            <li>
                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--::::: TOP BAR END :::::::-->

<div class="border_black"></div>

<!--::::: LOGO AREA START  :::::::-->
<div class="logo_area white_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 align-self-center">
                <div class="">
                    <a href="{% url 'app:home' %}">
                        <img src="{% static 'assets/img/logo/TIT_kolor_logo.png' %}" alt="image" style="width:10000px;">
                    </a>
                </div>
            </div>
            <div class="col-lg-8 align-self-center">
                {% if object.add_navbar %}
                    <div class="banner1 openModalClass" onclick="passDataFunction('add_navbar')">
                        {% if object.add_navbar.add %}
                        <a href="{{ object.add_navbar.url }}" target="_blank">
                            <img src="{{ object.add_navbar.img_728x90.url }}" alt="">
                        </a>
                        {% else %}
                        <a href="/artykul/{{ object.add_navbar.slug }}/" target="_self">
                            <img src="{{ object.add_navbar.img_728x90.url }}" alt="">
                        </a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!--::::: LOGO AREA END :::::::-->


<!--::::: MENU AREA START  :::::::-->
<div class="main-menu otger_bg" id="header"><a href="#top" class="up_btn up_btn1"><i
        class="far fa-chevron-double-up"></i></a>
    <div class="main-nav clearfix is-ts-sticky">
        <div class="container">
            <div class="row justify-content-between">

                <div class="col-6 col-lg-8">
                    <div class="newsprk_nav stellarnav">
                        <ul id="newsprk_menu">
                            <li><a href="/ogloszenia/">Ogłoszenia <i class="fal fa-angle-down"></i></a>

                                <ul>
                                     <li>
                                            <a href="/ogloszenia/create/">Add ads</a>
                                     </li>
                                    {% get_add_category as app_category %}
                                    {% for item in app_category %}
                                        <li>
                                            <a href="/ogloszenia/{{ item.slug }}/">{{ item.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li><a href="/artykuly/">Artykuły <i class="fal fa-angle-down"></i></a>
                                <ul>
                                    {% for cat in categories %}
                                        <li>
                                            <a href="/artykuly/{{ cat.slug }}/">{{ cat.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li><a href="{% url 'app:contact' %}">Kontakt</a></li>
                            <li><a href="/full_access/">Pełny dostęp</a></li>
                            <li><a href="#">Cennik <i class="fal fa-angle-down"></i></a>
                                <ul>
                                    <li><a href="{% url 'app:pricing_paper' %}">Wydanie gazetowe</a>
                                    </li>
                                    <li><a href="{% url 'app:pricing_internet' %}">Wydanie internetowe</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="{% url 'app:articles' 1 %}">Komunikaty</a></li>
                        </ul>
                    </div>

                </div>
                <div class="col-6 col-lg-4 align-self-center">
                    <div class="menu_right">
                        <div class="users_area">
                            <ul class="inline">
                                <li class="search_btn"><i class="far fa-search"></i>
                                </li>
                                <a href="#">
                                    <li>
                                        <i class="fal fa-user-circle"></i>
                                    </li>
                                </a>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--::::: MENU AREA END :::::::-->
  

app/templates/app/basic/right-section.html
{% load static %}
{% load app_tags %}

<div class="col-md-6 col-lg-4">
    <div class="widget_tab md-mt-30">

        <div class="tab-content">
            <div id="post1" class="tab-pane fade show in active">
                <div class="widget tab_widgets mb30">

                    <a href="https://www.sklep.tomaszow-tit.pl/tit-tomaszowski-informator-tygodniowy">
                        <img src="{% static 'assets/img/gallary/1g.jpg' %}" alt="">
                    </a>
                    <a class="btn btn-block btn-danger mt10"
                       href="https://www.sklep.tomaszow-tit.pl/tit-tomaszowski-informator-tygodniowy">Kup najnowsze
                        wydanie TIT w PDF!</a>

                    <div class="space-15"></div>
                    <div class="border_black"></div>
                    <div class="space-15"></div>

                </div>
            </div>
        </div>

          <div class="tab-content">
            <div class="tab-pane fade show in active">
                <div class="widget tab_widgets mb30">

                    <a href="https://www.sklep.tomaszow-tit.pl/tit-tomaszowski-informator-tygodniowy">
                        <img src="{% static 'assets/img/gallary/1g.jpg' %}" alt="">
                    </a>
                    <a class="btn btn-block btn-primary mt10"
                       href="https://www.sklep.tomaszow-tit.pl/tit-tomaszowski-informator-tygodniowy">Kup najnowsze
                        wydanie TIT w PDF!</a>

                    <div class="space-15"></div>
                    <div class="border_black"></div>
                    <div class="space-15"></div>

                </div>
            </div>
        </div>

        <!--:::::: POST TYPE 4 END :::::::-->
        <div class="box widget news_letter mb30">
            <h2 class="widget-title">Newsletter</h2>
            <p>Powiadomimy cię o nowych artykułach pojawiających się na łamach naszego tygodnika.</p>
            <div class="space-20"></div>
            <div class="signup_form">
                {% get_subscribe_form as s_form %}
                <form action="/subscribe_email/" method="post" id="subscribe_email" >
                    {% csrf_token %}
                    {{ s_form.email }}
                    <input type="submit" class="cbtn" value="Zapisz" >
                </form>
                <div class="space-10"></div>
                <span id="subscribe_msg" class="text-primary font14"></span>
                <p>Podając adres email, akceptujesz regulamin i politykę prywatności.</p>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'assets/js/plugins/jquery.2.1.0.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery.form.js' %}"></script>
<script>
    $('#subscribe_email').ajaxForm({
        success:function(data)
        {
            $('#subscribe_msg').text(data.status);
        }
    });

</script>