app/urls.py
from django.urls import path
from . import views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('artykuly/', views.articles, name='article'),
    path('artykul/<slug:slug>/', views.article, name='article'),
    path('comment/', views.comment, name='comment'),
    path('drobne-ogloszenia/<slug:slug>/', views.small_ads, name='small_ads'),
    path('artykuly/<slug:slug>/', views.articles, name='articles'),
    path('cennik/wydanie-gazetowe/', views.pricing_paper, name='pricing_paper'),
    path('cennik/wydanie-internetowe/', views.pricing_internet, name='pricing_internet'),
    path('wyszukiwarka/', views.search, name='search'),
    path('o-nas/', views.about, name='about'),
    path('kontakt/', views.contact, name='contact'),
    path('polityka-prywatnosci/', views.privacy, name='privacy'),
    path('regulamin-strony/', views.regulations, name='regulations'),
    path('ogloszenia/create/', views.add_create, name='add_create'),
    path('ogloszenia/', views.add_list, name='add_list'),
    path('ogloszenia/<slug:slug>/', views.add_list, name='add_list'),
    path('ogloszenia_detail/<slug:slug>/', views.add_detail, name='add_list'),
    path('subscribe_email/', views.subscribe_email, name='subscribe_email'),
    path('payment_ok/', views.payment_ok, name='payment_ok'),
    path('payment_error/', views.payment_ok, name='payment_error'),
    path('full_access/', views.full_access, name='full_access'),
    path('subscribe/', views.subscribe, name="subscribe"),
    path('update_user/', views.update_user, name='update_user'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('uwierzytelnienie/', include('authentication.urls', namespace='authentication')),
    path('cms/', include('simple_cms.urls', namespace='simple_cms')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from .views import LogIn, SignUp

app_name = 'authentication'

urlpatterns = [
    path('', LogIn.as_view(), name='login'),
    path('nowe-konto/', SignUp.as_view(), name='signup'),
]

app/models.py
from ckeditor.fields import RichTextField
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
from imagekit.processors import ResizeToFit

from authentication.models import CustomUser
from . import const
import datetime
from dateutil.relativedelta import *


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nazwa kategorii')
    menu = models.BooleanField(default=False, verbose_name='Pokaż w menu')
    slug = models.SlugField(unique=True, max_length=500, null=True, blank=True)

    class Meta:
        verbose_name = 'Kategorie artykułów'
        verbose_name_plural = 'Kategorie artykułów'

    def __str__(self):
        return self.name


class Autor(models.Model):
    name = models.CharField(max_length=50, verbose_name='Imię i nazwisko')
    pseudonym = models.CharField(max_length=50, verbose_name='Pseudonim')
    img = ProcessedImageField(upload_to='profile-pictures',
                              processors=[ResizeToFill(400, 400)],
                              format='JPEG',
                              options={'quality': 100},
                              verbose_name='Zdjęcie (proferowany format 400x400)')
    description = models.TextField(null=True, verbose_name='Opis (opcjonalnie)')
    show_img = models.BooleanField(default=False, verbose_name='Pokaż zdjęcie użytkownika')

    class Meta:
        verbose_name = 'Autorzy'
        verbose_name_plural = 'Autorzy'

    def __str__(self):
        return self.name


class Article(models.Model):
    owner = models.ForeignKey(Autor, on_delete=models.CASCADE, verbose_name='Autor')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategoria artykułu')
    title = models.CharField(max_length=100, verbose_name='Tytuł artykułu')
    subtitle = models.TextField(verbose_name='Rozszerzenie tytulu artykulu')
    slug = models.SlugField(verbose_name="URL artykułu (zmieniać w ramach konieczności):", unique=True)
    img_classic = ProcessedImageField(upload_to='profile-pictures',
                                      verbose_name='Zdjęcie (proferowany format 730x450)',
                                      processors=[ResizeToFit(1920, 1920)],
                                      format='JPEG',
                                      options={'quality': 100})
    img = ImageSpecField(source='img_classic',
                         processors=[ResizeToFill(730, 450)],
                         format='JPEG',
                         options={'quality': 100})
    basic_img = ImageSpecField(source='img_classic',
                               processors=[ResizeToFill(1460, 1000)],
                               format='JPEG',
                               options={'quality': 80})
    img_95x70 = ImageSpecField(source='img_classic',
                               processors=[ResizeToFill(95, 70)],
                               format='JPEG',
                               options={'quality': 80})
    img_190x140 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(190, 140)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_200x154 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(200, 154)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_728x90 = ImageSpecField(source='img_classic',
                                processors=[ResizeToFill(728, 90)],
                                format='JPEG',
                                options={'quality': 80})
    img_700x500 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(700, 500)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_360x115 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(360, 115)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_160x128 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(160, 128)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_1080x840 = ImageSpecField(source='img_classic',
                                  processors=[ResizeToFill(1080, 840)],
                                  format='JPEG',
                                  options={'quality': 80})
    img_1460x822 = ImageSpecField(source='img_classic',
                                  processors=[ResizeToFill(1460, 822)],
                                  format='JPEG',
                                  options={'quality': 80})
    img_200x113 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(200, 113)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_540x640 = ImageSpecField(source='img_classic',
                                 processors=[ResizeToFill(540, 640)],
                                 format='JPEG',
                                 options={'quality': 80})

    date_of_publication = models.DateTimeField(verbose_name='Data publikacji')
    content = RichTextField(verbose_name='Treść artykułu')
    premium = models.BooleanField(default=True, verbose_name='Widoczne tylko dla PREMIUM')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    add = models.BooleanField(default=False, verbose_name='Czy artykuł jest reklamą?')
    url = models.URLField(blank=True, null=True, verbose_name='Adres URL reklamy')

    class Meta:
        verbose_name = 'Artykuły'
        verbose_name_plural = 'Artykuły'

    def __str__(self):
        return self.title


class Comment(models.Model):
    owner = models.ForeignKey(Article,
                              on_delete=models.CASCADE,
                              related_name='comments',
                              verbose_name='Artykuł')
    name = models.CharField(max_length=30, verbose_name='Imie lub pseudonim')
    user = models.ForeignKey(CustomUser,
                             on_delete=models.CASCADE,
                             blank=True,
                             null=True,
                             verbose_name='Jeżeli dodawał zalogowany użytkownik')
    content = models.TextField(verbose_name='Treść dodawanej opinii')
    display = models.BooleanField(default=False, verbose_name='Widoczny komentarz')

    class Meta:
        verbose_name = 'Komentarze użytkowników'
        verbose_name_plural = 'Komentarze użytkowników'

    def __str__(self):
        return '%s - %s | Widoczny: %s' % (self.name, self.owner.title, self.display)


class AddCategory(models.Model):
    name = models.CharField(max_length=100, null=True)
    slug = models.SlugField(verbose_name='slug for Category', unique=True, max_length=500)
    img_url = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Add(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    category = models.ForeignKey(AddCategory, verbose_name="Category", related_name='adds',
                                 on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name='slug', unique=True, max_length=500)
    background_img = ProcessedImageField(upload_to='add-pictures',
                                         verbose_name='background image',
                                         processors=[ResizeToFill(1920, 1080)],
                                         format='JPEG',
                                         options={'quality': 100}, blank=True, null=True)
    img_300x170 = ImageSpecField(source='background_img',
                                 processors=[ResizeToFill(300, 170)],
                                 format='JPEG',
                                 options={'quality': 80})
    img_730x411 = ImageSpecField(source='background_img',
                                 processors=[ResizeToFill(730, 411)],
                                 format='JPEG',
                                 options={'quality': 80})

    content = models.TextField(verbose_name="Content", blank=True, null=True, default='')
    phone_number = models.CharField(blank=True, null=True, max_length=30)
    featured = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    words = models.IntegerField(default=0)
    time_of_broadcast = models.IntegerField(verbose_name='Time of broadcast(weeks)', default=1)
    price = models.DecimalField(max_digits=5, decimal_places=1, default=0)

    def __str__(self):
        return self.content


class PrivacyPolicy(models.Model):
    privacy = RichTextField()
    regulations = RichTextField()

    class Meta:
        verbose_name = 'Polityka prywatności i regulamin'
        verbose_name_plural = 'Polityka prywatności i regulamin'


class SubscriberEmail(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class AdsSetting(models.Model):
    word_limit = models.IntegerField(default=500)
    price_word = models.DecimalField(decimal_places=1, max_digits=2, default=1.0)
    price_image = models.DecimalField(decimal_places=1, max_digits=3, default=10.0)
    tax_rate = models.DecimalField(decimal_places=3, max_digits=4, default=0.074)


class ContactMessage(models.Model):
    name = models.CharField(max_length=100, null=True, )
    email = models.EmailField(max_length=100, null=True, )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

app/templates/app/add_create.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
    <title>{{ obj.title }} - TIT - Tomaszowski Informator Tygodniowy</title>
    <!-- META -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--::::: FABICON ICON :::::::-->
    <link rel="icon" href="{% static 'assets/img/icon/fabicon.png' %}">
    <!--::::: ALL CSS FILES :::::::-->
    <link rel="stylesheet" href="{% static 'assets/css/plugins/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/stellarnav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/modal-video.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>

<body class="theme-1">
{% include "app/basic/navbar.html" %}

<!--::::: ARCHIVE AREA START :::::::-->
<div class="archives post post1 padding-top-30">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="bridcrumb"><a href="#">Strona główna</a> / ogloszenia / create /</div>
            </div>
        </div>
        <div class="space-30"></div>
        <div class="row">
            <div class="col-md-6 col-lg-8">
                <span class="font14" >Word Limit: <span id="words-limits">{{ ads_setting.word_limit }}</span></span> <br>
                <span class="font14">Price per Word: <span id="price-word">{{ ads_setting.price_word }}</span> zł <span class="multiple"> * </span><span class="weeks">1</span></span>

                <div class="space-15"></div>
                <div class="border_black"></div>
                <div class="space-15"></div>

                <span class="font14">Words count: <span id="id_words_count">0</span> </span> <br>
                <span class="font14">Price for the words entered: <span id="price-word-all"></span>  zł  </span><br>

                <div class="space-15"></div>
                <div class="border_black"></div>
                <div class="space-15"></div>

                <form action="" method="post" enctype="multipart/form-data" class="comment_form">
                    {% csrf_token %}
                    {% for fields in form %}
                        <label for="id_{{ fields.name }}">{{ fields.label }} </label>

                        {% if fields.name == 'background_img' %}
                            <div class="space-5"></div>
                            <span class="font14">Price for an additional photo: <span id="price_image">{{ ads_setting.price_image }}</span> zł <span class="multiple"> * </span> <span class="weeks">1</span> </span><br>
                            <div class="space-15"></div>
                        {% endif %}

                        {% if fields.name == 'time_of_broadcast' %}
                            <select name="time_of_broadcast" class="form-control mb-4" id="id_{{ fields.name }}">
                            {% for index in array_52 %}
                                <option value="{{ index }}">{{ index }} </option>
                            {% endfor %}
                            </select>
                        {% elif fields.name == 'phone_number' %}
                            <input type="text" name="phone_number" {{ request.user.is_authenticated|yesno:',required' }} class="form-control px-1  mb-4" maxlength="30" id="id_phone_number">
                        {% elif fields.name == 'background_img' %}
                            <div class="custom-file mb-3">
                              {{ fields | safe }}
                              <label class="custom-file-label" for="customFile"></label>
                            </div>
                        {% else %}
                            {{ fields | safe }}
                        {% endif %}
                        <br>
                    {% endfor %}

                    <input type="text" name="words" class="form-control d-none" required="" id="id_words">
                    <input type="text" name="price" class="form-control d-none" required="" id="id_price">
                    <span class="font14">Total price is : <span id="total_price">0</span> zł </span> <br>
                    <span id="words-limit-msg" class="text-danger">Words limit exceed! You can't submit!</span>
                    <button type="submit" class="btn btn-primary" id="btn-submit" style="float:right;"> Submit </button>
                </form>

            </div>

            {% include "app/basic/right-section.html" %}
        </div>
    </div>
</div>
<!--::::: ARCHIVE AREA END :::::::-->
<div class="space-60"></div>
<!--::::: LATEST BLOG AREA START :::::::-->
{% include 'app/basic/latest_article.html' %}

<!--:::::  COMMENT FORM AREA END :::::::-->
<!--::::: BANNER AREA START :::::::-->
{% include 'app/basic/footer_banner.html' %}
<!--::::: BANNER AREA END :::::::-->
<!--::::: FOOTER AREA START :::::::-->
{% include "app/basic/footer.html" %}

<!--::::: FOOTER AREA END :::::::-->
<!--::::: ALL JS FILES :::::::-->
<script src="{% static 'assets/js/plugins/jquery.2.1.0.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery.nav.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery-modal-video.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/owl.carousel.js' %}"></script>
<script src="{% static 'assets/js/plugins/popper.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/circle-progress.js' %}"></script>
<script src="{% static 'assets/js/plugins/slick.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/wow.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/stellarnav.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script>

    var words_limit = parseInt($('#words-limits').text());

    $(document).on('ready', function () {
            $('.weeks').hide();
            $('.multiple').hide();
            $('#words-limit-msg').hide();
    });

    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      total_price();
    });

    $('#id_time_of_broadcast').on("change", function () {
        let week = $(this).val();
        $('.weeks').text(week);
        if(week > 1){
            $('.weeks').show();
            $('.multiple').show();
        }
        else{
            $('.weeks').hide();
            $('.multiple').hide();
        }

        total_price();

    });

    $('#id_featured').on('change', function () {
        total_price();
    });

    $(document).on('keyup', '#id_content', function () {
        let str = $(this).val();
        $('#id_slug').val(string_to_slug(str));
        $('#id_words_count').text(counts_word(str));
        $('#id_words').val(counts_word(str));

        if(counts_word(str) > words_limit){
            $('#words-limit-msg').show();
            document.getElementById("btn-submit").disabled = true;

        }
        else{
            $('#words-limit-msg').hide();
            document.getElementById("btn-submit").disabled = false;
        }


        total_price();
    });

    function total_price() {
        let featured = $('#id_featured').is(":checked");
        console.log(featured);
        let feature_val = ((featured) ? 2 : 1) ;
        console.log(feature_val);
        let week = parseInt($('#id_time_of_broadcast').val());


        let word_price =  parseFloat( $('#price-word').text() );
        let word_counts = parseInt(  $('#id_words_count').text() );
        let word_price_all = word_price * word_counts * week * feature_val;
        $('#price-word-all').text(word_price_all);


        let image_price = 0;
        if ($('#id_background_img').val()){
            image_price = $('#price_image').text();
        }

        $('#id_price').val(parseFloat(word_price_all) + parseFloat(image_price) * week );
        $('#total_price').text(parseFloat(word_price_all) + parseFloat(image_price) * week );
        return parseFloat(word_price_all) + parseFloat(image_price);
    }

    function counts_word(str) {
        str = str.replace(/(^\s*)|(\s*$)/gi,"");
        str = str.replace(/[ ]{2,}/gi," ");
        str = str.replace(/\n /,"\n");
        return str.split(' ').length;
    }

    function string_to_slug(str) {
        str = str.replace(/^\s+|\s+$/g, ''); // trim
        str = str.toLowerCase();

        // remove accents, swap ñ for n, etc
        var from = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;";
        var to = "aaaaeeeeiiiioooouuuunc------";
        for (var i = 0, l = from.length; i < l; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
        }

        str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '-') // collapse whitespace and replace by -
            .replace(/-+/g, '-'); // collapse dashes

        return str;
    }
</script>
</body>

</html>

app/templates/app/add_detail.html
{% load static %}
{% load app_tags %}
<!DOCTYPE html>
<html lang="pl">

<head>
  <title>{{ obj.title }} - TIT - Tomaszowski Informator Tygodniowy</title>
  <!-- META -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!--::::: FABICON ICON :::::::-->
  <link rel="icon" href="{% static 'assets/img/icon/fabicon.png' %}">
  <!--::::: ALL CSS FILES :::::::-->
  <link rel="stylesheet" href="{% static 'assets/css/plugins/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/stellarnav.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/modal-video.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/plugins/slick.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>

<body class="theme-1">
  {% include "app/basic/navbar.html" %}

  <!--::::: ARCHIVE AREA START :::::::-->
  <div class="archives post post1 padding-top-30">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="bridcrumb"> <a href="#">Strona główna</a> / ogloszenia / {{ obj.category.name }} / {{ obj.title }} </div>
        </div>
      </div>
      <div class="space-30"></div>
      <div class="row">
        <div class="col-md-6 col-lg-8">

          {% if obj.img_730x411 %}
            <img src="{{ obj.img_730x411.url }}" alt="image">
          {% endif %}
          <div class="mt-3">
              {{ obj.content }}
          </div>

        </div>


        {% include "app/basic/right-section.html" %}
      </div>
    </div>
  </div>
  <!--::::: ARCHIVE AREA END :::::::-->
  <div class="space-60"></div>
  <!--::::: LATEST BLOG AREA START :::::::-->
  {% include 'app/basic/latest_article.html' %}
  <!--::::: LATEST BLOG AREA END :::::::-->
  <!--::::: BANNER AREA START :::::::-->
    {% include 'app/basic/footer_banner.html' %}
  <!--::::: BANNER AREA END :::::::-->
  <!--::::: FOOTER AREA START :::::::-->
  {% include "app/basic/footer.html" %}

  <!--::::: FOOTER AREA END :::::::-->
  <!--::::: ALL JS FILES :::::::-->
  <script src="{% static 'assets/js/plugins/jquery.2.1.0.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.nav.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery-modal-video.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/owl.carousel.js' %}"></script>
  <script src="{% static 'assets/js/plugins/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/circle-progress.js' %}"></script>
  <script src="{% static 'assets/js/plugins/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/wow.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/stellarnav.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

app/templates/app/order.html
{% load static %}
{% load app_tags %}
<!DOCTYPE html>
<html lang="pl">

<head>
    <title>Tomaszów Mazowiecki - TIT - Lista artykułów.</title>
    <!-- META -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--::::: FABICON ICON :::::::-->
    <link rel="icon" href="{% static 'assets/img/icon/fabicon.png' %}">
    <!--::::: ALL CSS FILES :::::::-->
    <link rel="stylesheet" href="{% static 'assets/css/plugins/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/modal-video.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/stellarnav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
    <style>
        .myDiv {
            background: #1191ff;
        }

        td {
            padding: 12px;
        }
    </style>
</head>

<body class="theme-1">
<!--::::: PRELOADER START :::::::-->
{% include "app/basic/navbar.html" %}

<!--::::: ARCHIVE AREA START :::::::-->

<!--::::: ARCHIVE AREA END :::::::-->
<div class="archives padding-top-30">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8">
                <h3>User Information for Subscription</h3>
                <p class="mt-3 font12">Please enter your information for Full Access Subsciption.</p>
                <form action="https://sandbox.przelewy24.pl/index.php" method="post" id="payment_frm" onsubmit="onpay()"
                      class="mt-4">
                    {% for fields in order_form %}
                        {% if fields.label %}
                            <label for="id_{{ fields.name }}" class="font-weight-bold">{{ fields.label }}</label>
                        {% endif %}
                        {{ fields|safe }}
                    {% endfor %}

                    <div class="mt-4">
                        <h3>Payment Information</h3>
                        <div class="space-15"></div>
                        <div class="border_black"></div>

                        <table>
                            <tbody>
                            <tr>
                                <td>Price:</td>
                                <td>{{ payment_ins.price|floatformat:2 }}</td>
                                <td>zł</td>
                            </tr>
                            <tr>
                                <td>Tax Rule:</td>
                                <td>{{ payment_ins.tax_rule|floatformat:2 }}</td>
                                <td>zł</td>
                            </tr>
                            <tr>
                                <td>Total:</td>
                                <td>{{ payment_ins.total|floatformat:2 }}</td>
                                <td>zł</td>
                            </tr>
                            </tbody>
                        </table>

                    </div>

                    <input type="submit" class="form-control btn btn-primary" value="Pay Now">
                </form>

            </div>


            {% include 'app/basic/right-section.html' %}
        </div>
    </div>
</div>
<!--::::: BANNER AREA START :::::::-->
{% include 'app/basic/footer_banner.html' %}
<!--::::: BANNER AREA END :::::::-->
<!--::::: FOOTER AREA START :::::::-->
{% include "app/basic/footer.html" %}

<!--::::: FOOTER AREA END :::::::-->
<!--::::: ALL JS FILES :::::::-->
<script src="{% static 'assets/js/plugins/jquery.2.1.0.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery.nav.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/jquery-modal-video.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/owl.carousel.js' %}"></script>
<script src="{% static 'assets/js/plugins/popper.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/circle-progress.js' %}"></script>
<script src="{% static 'assets/js/plugins/slick.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/stellarnav.js' %}"></script>
<script src="{% static 'assets/js/plugins/wow.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

<script>
    function onpay() {
        var data = $('#payment_frm').serialize();
        var token = '{{csrf_token}}';
        $.ajax({
            headers: {
                "X-CSRFToken": token
            },
            url: '/update_user/',
            type: 'post',
            data: data,
            success: function (data) {
                console.log(data);
            }
        });
    }
</script>
</body>

</html>